---
apiVersion: v1
kind: Service
metadata:
  name: hango-api-plane
  namespace: {{ .Values.namespace }}
  labels:
    app: hango-api-plane
spec:
  type: ClusterIP
  ports:
  - port: 10880
    targetPort: 10880
    name: http
  selector:
    app: hango-api-plane

---
apiVersion: v1
kind: Service
metadata:
  name: hango-portal
  namespace: {{ .Values.namespace }}
  labels:
    app: hango-portal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 11113
  selector:
    app: hango-portal

---
apiVersion: v1
kind: Service
metadata:
  name: hango-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: hango-ui
spec:
  type: NodePort
  ports:
  - port: 8789
    targetPort: 8789
    protocol: TCP
  selector:
    app: hango-ui

---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: {{ .Values.namespace }}
  labels:
    app: istiod
    istio: pilot
    istio.io/rev: {{ .Values.istio_rev }}
spec:
  ports:
    - port: 15010
      name: grpc-xds # plaintext
    - port: 15012
      name: https-dns # mTLS with k8s-signed cert
    - port: 443
      name: https-webhook # validation and injection
      targetPort: 15017
    - port: 15014
      name: http-monitoring # prometheus stats
    - port: 8080
      name: http-legacy-discovery
  selector:
    app: istiod
    istio.io/rev: {{ .Values.istio_rev }}

---
apiVersion: v1
kind: Service
metadata:
  name: slime
  namespace: {{ .Values.namespace }}
  labels:
    app: slime
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: aux-port
      protocol: TCP
      name: aux-port
    - port: 8082
      targetPort: log-source-port
      protocol: TCP
      name: log-source-port
  selector:
    app: slime

---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hango-proxy
  name: hango-proxy
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 8301
      targetPort: 8301
      protocol: TCP
      name: admin
    - port: 19000
      targetPort: 19000
      protocol: TCP
      name: stats
  selector:
    app: hango-proxy
  type: NodePort


