apiVersion: v1
kind: ServiceAccount
metadata:
  name: hango-apiplane
  namespace: {{ .Values.namespace }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istiod-service-account
  namespace: {{ .Values.namespace }}
  labels:
    app: istiod

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: slime-hango
  namespace: {{ .Values.namespace }}
  labels:
    app: slime-hango


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hango-apiplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: hango-apiplane
    namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: slime-hango
subjects:
  - kind: ServiceAccount
    name: slime-hango
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hango-istiod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: istiod-service-account
    namespace: {{ .Values.namespace }}

---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  labels:
    istio.io/rev: {{ .Values.istio_rev }}
  name: istiod
  namespace: {{ .Values.namespace }}
spec:
  mtls:
    mode: DISABLE
