---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: hango-gateway
  namespace: hango-system
spec:
  components:
    ingressGateways:
      - enabled: true
        k8s:
          overlays:
            - kind: Deployment
              name: gateway-proxy
              patches:
                - path: spec.template.spec.volumes[10]
                  value: |-
                    name: hango-rider-plugin
                    configMap:
                      name: hango-rider-plugin
                      defaultMode: 420
                - path: spec.template.spec.containers[0].volumeMounts[100]
                  value: |-
                    name: hango-rider-plugin 
                    mountPath: /usr/local/lib/rider/plugins
          podAnnotations:
            proxy.istio.io/config: '{"discoveryAddress" : "istiod.hango-system.svc.cluster.local:15010","controlPlaneAuthPolicy":"NONE","proxyStatsMatcher": {"inclusionPrefixes":["cluster", "listener","http"]}}'
          service:
            selector:
              app: gateway-proxy
            type: NodePort
        label:
          app: gateway-proxy
          gw_cluster: demo-istio
        name: gateway-proxy
    pilot:
      enabled: false
  profile: minimal
  values:
    global:
      istioNamespace: hango-system
      proxy:
        image: hangoio/envoy-proxy-rider:master_baa64381_27a94f2