data_dir: /data
cluster_dns_domain: cluster.local

images:
  hango_apiplane_image: hangoio/api-plane:2.1.0
  hango_portal_image: hangoio/hango-portal:2.1.0
  hango_ui_image: hangoio/hango-ui:v2.1.0
  istiod_image: hangoio/pilot:hango-2.1.0
  slime_image: docker.io/slimeio/slime-bundle-hango:hango-v1.3.0
  hango_proxy_image: hangoio/envoy-proxy:hango-v2.1.0-112caf6

namespace: hango-system

replicas: 1
istio_rev: gw-1.12

gateway_xds_service_address: istiod.hango-system.svc.cluster.local
gateway_xds_service_security_port: 15012
gateway_xds_service_port: 15010
gateway_cluster: hango-demo-gateway

slime:
  cfg:
    global:
      log:
        klogLevel: 5
        logLevel: info
      misc:
        seLabelSelectorKeys: projectName

registry:
  nacos:
    ## nacos注册中心功能开关（true 或 false）
    enable: false
    ## 注册中心实例地址；格式：整体以英文单引号包裹，单个地址以英文双引号包裹，多个地址用英文逗号分隔
    address: '"http://127.0.0.1:8848"'
    ## nacos客户端服务所在分组
    service_group: hango_demo
  eureka:
    ## eureka注册中心功能开关（true 或 false）
    enable: false
    ## 刷新eureka服务缓存的时间周期，默认15s，格式为: [正整数]s
    refresh_period: 15s
    ## 注册中心实例地址；格式：整体以英文单引号包裹，单个地址以英文双引号包裹，多个地址用英文逗号分隔
    address: '"http://127.0.0.1:8761/eureka"'
  zk:
    ## zookeeper注册中心功能开关（true 或 false）
    enable: false
    ## 刷新zookeeper服务缓存的时间周期，默认15s，格式为: [正整数]s
    refresh_period: 15s
    ## 注册中心实例地址；格式：整体以英文单引号包裹，单个地址以英文双引号包裹，多个地址用英文逗号分隔
    address: '"zookeeper.apigw-demo.svc.cluster.local:2181"'
