data_dir: /data
cluster_dns_domain: cluster.local

images:
  hango_apiplane_image: docker.io/hangoio/api-plane:latest
  hango_portal_image: docker.io/hangoio/hango-portal:latest
  hango_ui_image: docker.io/hangoio/hango-ui:v1.0.1-f7ddf75e
  istiod_image: docker.io/hangoio/istiod:hango-1.0.0-rc1
  slime_image: docker.io/slimeio/slime-bundle-hango:v0.5.0_linux_amd64
  hango_proxy_image: hangoio/envoy-proxy:v1.1.0-46f6660-amd64


namespace: hango-system

replicas: 1
istio_rev: gw-1.12

gateway_xds_service_address: istiod.hango-system.svc.cluster.local
gateway_xds_service_security_port: 15012
gateway_xds_service_port: 15010
gateway_cluster: demo-istio

slime:
  cfg:
    global:
      log:
        klogLevel: 5
        logLevel: info
      misc:
        seLabelSelectorKeys: projectName
